# Generated by Django 2.0.7 on 2018-09-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('fromwho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nadawca', to=settings.AUTH_USER_MODEL)),
                ('towho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
