# Generated by Django 2.0.7 on 2018-09-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwik', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
